backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

logo_url: "https://capci.com.ar/images/logo.png"
media_folder: "static/images/uploads"

collections:
  - name: "miembros" # Used in routes, e.g., /admin/collections/blog
    label: "Miembros" # Used in the UI
    folder: "content/miembros" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: "nombre"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Imagen", name: "imagen", widget: "image"}
      - {label: "Info", name: "info", widget: "markdown"}